packages:
  - "apps/*"
  - "packages/*"
nodeLinker: hoisted
allowBuilds:
  '@sentry/cli': set this to true or false
  "@swc/core": true
  esbuild: true
  ffmpeg-static: true
  lightningcss: true
  msw: true
  protobufjs: true
