/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsModelSlugRouteImport } from './routes/models_.$modelSlug'
import { Route as ExploreCategoryRouteImport } from './routes/explore_.$category'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppWorkspaceRouteImport } from './routes/app._workspace'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppWorkspaceIndexRouteImport } from './routes/app._workspace.index'
import { Route as AppSettingsCreditsRouteImport } from './routes/app.settings.credits'
import { Route as AppAdminImpersonationRouteImport } from './routes/app.admin.impersonation'
import { Route as AppWorkspaceThreadsThreadIdRouteImport } from './routes/app._workspace.threads.$threadId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelSlugRoute = ModelsModelSlugRouteImport.update({
  id: '/models_/$modelSlug',
  path: '/models/$modelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/explore_/$category',
  path: '/explore/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppSettingsCreditsRoute = AppSettingsCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAdminImpersonationRoute = AppAdminImpersonationRouteImport.update({
  id: '/impersonation',
  path: '/impersonation',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppWorkspaceThreadsThreadIdRoute =
  AppWorkspaceThreadsThreadIdRouteImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/explore/$category': typeof ExploreCategoryRoute
  '/models/$modelSlug': typeof ModelsModelSlugRoute
  '/models/': typeof ModelsIndexRoute
  '/app/admin/impersonation': typeof AppAdminImpersonationRoute
  '/app/settings/credits': typeof AppSettingsCreditsRoute
  '/app/': typeof AppWorkspaceIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/threads/$threadId': typeof AppWorkspaceThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppWorkspaceIndexRoute
  '/check-email': typeof CheckEmailRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/explore/$category': typeof ExploreCategoryRoute
  '/models/$modelSlug': typeof ModelsModelSlugRoute
  '/models': typeof ModelsIndexRoute
  '/app/admin/impersonation': typeof AppAdminImpersonationRoute
  '/app/settings/credits': typeof AppSettingsCreditsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/threads/$threadId': typeof AppWorkspaceThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/_workspace': typeof AppWorkspaceRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/explore_/$category': typeof ExploreCategoryRoute
  '/models_/$modelSlug': typeof ModelsModelSlugRoute
  '/models/': typeof ModelsIndexRoute
  '/app/admin/impersonation': typeof AppAdminImpersonationRoute
  '/app/settings/credits': typeof AppSettingsCreditsRoute
  '/app/_workspace/': typeof AppWorkspaceIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/_workspace/threads/$threadId': typeof AppWorkspaceThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/check-email'
    | '/explore'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/app/admin'
    | '/app/settings'
    | '/explore/$category'
    | '/models/$modelSlug'
    | '/models/'
    | '/app/admin/impersonation'
    | '/app/settings/credits'
    | '/app/'
    | '/app/admin/'
    | '/app/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/check-email'
    | '/explore'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/app/settings'
    | '/explore/$category'
    | '/models/$modelSlug'
    | '/models'
    | '/app/admin/impersonation'
    | '/app/settings/credits'
    | '/app/admin'
    | '/app/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/check-email'
    | '/explore'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/app/_workspace'
    | '/app/admin'
    | '/app/settings'
    | '/explore_/$category'
    | '/models_/$modelSlug'
    | '/models/'
    | '/app/admin/impersonation'
    | '/app/settings/credits'
    | '/app/_workspace/'
    | '/app/admin/'
    | '/app/_workspace/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ExploreRoute: typeof ExploreRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ExploreCategoryRoute: typeof ExploreCategoryRoute
  ModelsModelSlugRoute: typeof ModelsModelSlugRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/$modelSlug': {
      id: '/models_/$modelSlug'
      path: '/models/$modelSlug'
      fullPath: '/models/$modelSlug'
      preLoaderRoute: typeof ModelsModelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore_/$category': {
      id: '/explore_/$category'
      path: '/explore/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_workspace': {
      id: '/app/_workspace'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/_workspace/': {
      id: '/app/_workspace/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/settings/credits': {
      id: '/app/settings/credits'
      path: '/credits'
      fullPath: '/app/settings/credits'
      preLoaderRoute: typeof AppSettingsCreditsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/admin/impersonation': {
      id: '/app/admin/impersonation'
      path: '/impersonation'
      fullPath: '/app/admin/impersonation'
      preLoaderRoute: typeof AppAdminImpersonationRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/_workspace/threads/$threadId': {
      id: '/app/_workspace/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/app/threads/$threadId'
      preLoaderRoute: typeof AppWorkspaceThreadsThreadIdRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
  }
}

interface AppWorkspaceRouteChildren {
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
  AppWorkspaceThreadsThreadIdRoute: typeof AppWorkspaceThreadsThreadIdRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
  AppWorkspaceThreadsThreadIdRoute: AppWorkspaceThreadsThreadIdRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminImpersonationRoute: typeof AppAdminImpersonationRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminImpersonationRoute: AppAdminImpersonationRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsCreditsRoute: typeof AppSettingsCreditsRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsCreditsRoute: AppSettingsCreditsRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ExploreRoute: ExploreRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ExploreCategoryRoute: ExploreCategoryRoute,
  ModelsModelSlugRoute: ModelsModelSlugRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
