#!/usr/bin/env node

import { randomUUID } from "node:crypto";
import { pathToFileURL } from "node:url";

export const maxSafeInteger = 9_007_199_254_740_991n;
export const usdMicrosPerCent = 10_000n;

const canonicalUuidPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const controlCharacterPattern = /[\u0000-\u001f\u007f]/;

export function parseCliArgs(argv) {
  const values = new Map();

  for (let index = 0; index < argv.length; index += 1) {
    const name = argv[index];

    if (!name?.startsWith("--")) {
      throw new Error(`Unexpected argument: ${name ?? ""}`);
    }

    if (!["--user-id", "--amount-usd", "--grant-id"].includes(name)) {
      throw new Error(`Unknown option: ${name}`);
    }

    if (values.has(name)) {
      throw new Error(`Option may only be provided once: ${name}`);
    }

    const value = argv[index + 1];

    if (value === undefined || value.startsWith("--")) {
      throw new Error(`Missing value for ${name}`);
    }

    values.set(name, value);
    index += 1;
  }

  const userId = values.get("--user-id");
  const amountUsd = values.get("--amount-usd");

  if (userId === undefined || amountUsd === undefined) {
    const missingOptions = [
      ...(userId === undefined ? ["--user-id"] : []),
      ...(amountUsd === undefined ? ["--amount-usd"] : []),
    ];

    throw new Error(`Missing required option(s): ${missingOptions.join(", ")}`);
  }

  return {
    userId,
    amountUsd,
    grantId: values.get("--grant-id"),
  };
}

export function parseUserId(value) {
  if (value.length === 0) {
    throw new Error("User ID must not be empty");
  }

  if (value !== value.trim()) {
    throw new Error("User ID must not have leading or trailing whitespace");
  }

  if (controlCharacterPattern.test(value)) {
    throw new Error("User ID must not contain control characters");
  }

  return value;
}

export function parseAmountUsd(value) {
  const normalizedInput = value.trim();
  const match = /^\$?(0|[1-9]\d*)(?:\.(\d{1,2}))?$/.exec(normalizedInput);

  if (!match) {
    throw new Error(
      "USD amount must be positive and use at most two decimal places",
    );
  }

  const dollars = BigInt(match[1]);
  const centDigits = (match[2] ?? "").padEnd(2, "0");
  const amountCents = dollars * 100n + BigInt(centDigits || "0");

  if (amountCents <= 0n) {
    throw new Error("USD amount must be greater than zero");
  }

  const amountUsdMicros = amountCents * usdMicrosPerCent;

  if (amountUsdMicros > maxSafeInteger) {
    throw new Error(
      "USD amount exceeds the application's JavaScript-safe integer range",
    );
  }

  return {
    amountCents,
    amountUsdMicros,
    formattedAmountUsd: `$${amountCents / 100n}.${String(amountCents % 100n).padStart(2, "0")}`,
  };
}

export function parseGrantId(value) {
  if (!canonicalUuidPattern.test(value)) {
    throw new Error("Grant ID must be a canonical UUID");
  }

  return value.toLowerCase();
}

export function createSqlStringLiteral(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

export function createDollarQuoteTag(values, grantId) {
  const baseName = `grant_user_credits_${grantId.replaceAll("-", "")}`;
  let suffix = 0;

  while (true) {
    const tagName = suffix === 0 ? baseName : `${baseName}_${suffix}`;
    const tag = `$${tagName}$`;

    if (values.every((value) => !value.includes(tag))) {
      return tag;
    }

    suffix += 1;
  }
}

export function generateSql({
  userId: rawUserId,
  amountUsd: rawAmountUsd,
  grantId: rawGrantId,
}) {
  const userId = parseUserId(rawUserId);
  const { amountUsdMicros, formattedAmountUsd } = parseAmountUsd(rawAmountUsd);
  const grantId = parseGrantId(rawGrantId ?? randomUUID());
  const userIdLiteral = createSqlStringLiteral(userId);
  const grantIdLiteral = createSqlStringLiteral(grantId);
  const dollarQuoteTag = createDollarQuoteTag([userId], grantId);

  return `-- Generated by grant-user-credits-sql.
-- Recipient user ID: ${userId}
-- Grant amount: ${formattedAmountUsd} (${amountUsdMicros} USD micros)
-- Grant ID: ${grantId}
-- Keep the grant ID unchanged so this transaction cannot be applied twice.

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '15s';

DO ${dollarQuoteTag}
DECLARE
  grant_user_id CONSTANT text := ${userIdLiteral};
  grant_amount_usd_micros CONSTANT bigint := ${amountUsdMicros};
  grant_id CONSTANT text := ${grantIdLiteral};
  grant_ledger_entry_id CONSTANT text := 'admin-credit-adjustment:' || grant_id;
  grant_idempotency_key CONSTANT text := 'admin:credit-adjustment:' || grant_id;
  maximum_safe_integer CONSTANT bigint := ${maxSafeInteger};
  available_amount_before bigint;
  reserved_amount bigint;
  available_amount_after bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM "user"
    WHERE id = grant_user_id
  ) THEN
    RAISE EXCEPTION 'Remora user does not exist: %', grant_user_id;
  END IF;

  SELECT
    available_credit_amount_usd_micros,
    reserved_credit_amount_usd_micros
  INTO available_amount_before, reserved_amount
  FROM user_balance
  WHERE user_id = grant_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Credit balance is missing for Remora user: %', grant_user_id;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM billing_profile
    WHERE user_id = grant_user_id
  ) THEN
    RAISE EXCEPTION 'Billing profile is missing for Remora user: %', grant_user_id;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM credit_auto_top_up_settings
    WHERE user_id = grant_user_id
  ) THEN
    RAISE EXCEPTION 'Auto top-up settings are missing for Remora user: %', grant_user_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM credit_ledger_entry
    WHERE idempotency_key = grant_idempotency_key
  ) THEN
    RAISE EXCEPTION 'Admin credit grant has already been applied: %', grant_id;
  END IF;

  IF available_amount_before < -maximum_safe_integer
    OR available_amount_before > maximum_safe_integer
    OR reserved_amount < -maximum_safe_integer
    OR reserved_amount > maximum_safe_integer
  THEN
    RAISE EXCEPTION 'Existing credit balance is outside the application safe integer range for user: %', grant_user_id;
  END IF;

  IF available_amount_before > maximum_safe_integer - grant_amount_usd_micros THEN
    RAISE EXCEPTION 'Credit grant would exceed the application safe integer range for user: %', grant_user_id;
  END IF;

  available_amount_after := available_amount_before + grant_amount_usd_micros;

  UPDATE user_balance
  SET
    available_credit_amount_usd_micros = available_amount_after,
    updated_at = now()
  WHERE user_id = grant_user_id;

  INSERT INTO credit_ledger_entry (
    id,
    user_id,
    entry_type,
    available_credit_delta_usd_micros,
    reserved_credit_delta_usd_micros,
    available_credit_amount_usd_micros_after,
    reserved_credit_amount_usd_micros_after,
    idempotency_key,
    metadata
  ) VALUES (
    grant_ledger_entry_id,
    grant_user_id,
    'admin_credit_adjustment',
    grant_amount_usd_micros,
    0,
    available_amount_after,
    reserved_amount,
    grant_idempotency_key,
    jsonb_build_object(
      'reason', 'manual_admin_credit_grant',
      'grant_id', grant_id,
      'credit_amount_usd_micros', grant_amount_usd_micros,
      'generated_by', 'grant-user-credits-sql',
      'metadata_version', '1'
    )
  );
END;
${dollarQuoteTag} LANGUAGE plpgsql;

SELECT
  ledger.id AS ledger_entry_id,
  ledger.user_id,
  ledger.entry_type,
  ledger.available_credit_delta_usd_micros,
  ledger.available_credit_amount_usd_micros_after,
  ledger.reserved_credit_amount_usd_micros_after,
  balance.available_credit_amount_usd_micros AS current_available_credit_amount_usd_micros,
  balance.reserved_credit_amount_usd_micros AS current_reserved_credit_amount_usd_micros,
  ledger.idempotency_key,
  ledger.metadata,
  ledger.created_at
FROM credit_ledger_entry AS ledger
INNER JOIN user_balance AS balance ON balance.user_id = ledger.user_id
WHERE ledger.idempotency_key = 'admin:credit-adjustment:' || ${grantIdLiteral};

COMMIT;

-- Direct SQL bypasses realtime balance publication. The recipient may need to
-- refresh or reopen the app before the new balance appears.
`;
}

export function main(argv = process.argv.slice(2)) {
  const input = parseCliArgs(argv);
  process.stdout.write(generateSql(input));
}

const isDirectExecution =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectExecution) {
  try {
    main();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`Error: ${message}\n`);
    process.exitCode = 1;
  }
}
