INSERT INTO "generation_model_rate" (
  "id",
  "model_id",
  "component",
  "quantity_source",
  "final_quantity_source",
  "quantity_unit",
  "unit_quantity",
  "unit_price_usd_micros",
  "conditions"
)
VALUES
  (
    'kling-v3-text-to-video-output-video-720p-native-audio-off',
    'kling-v3-text-to-video',
    'output_video',
    'output_duration_seconds',
    NULL,
    'second',
    1,
    84000,
    '{"outputResolution":"720p","nativeAudio":false}'::jsonb
  ),
  (
    'kling-v3-text-to-video-output-video-1080p-native-audio-off',
    'kling-v3-text-to-video',
    'output_video',
    'output_duration_seconds',
    NULL,
    'second',
    1,
    112000,
    '{"outputResolution":"1080p","nativeAudio":false}'::jsonb
  ),
  (
    'kling-v3-text-to-video-output-video-4k-native-audio-off',
    'kling-v3-text-to-video',
    'output_video',
    'output_duration_seconds',
    NULL,
    'second',
    1,
    420000,
    '{"outputResolution":"4k","nativeAudio":false}'::jsonb
  ),
  (
    'kling-v3-text-to-video-output-video-720p-native-audio-on-voice-control-off',
    'kling-v3-text-to-video',
    'output_video',
    'output_duration_seconds',
    NULL,
    'second',
    1,
    126000,
    '{"outputResolution":"720p","nativeAudio":true,"voiceControl":false}'::jsonb
  ),
  (
    'kling-v3-text-to-video-output-video-1080p-native-audio-on-voice-control-off',
    'kling-v3-text-to-video',
    'output_video',
    'output_duration_seconds',
    NULL,
    'second',
    1,
    168000,
    '{"outputResolution":"1080p","nativeAudio":true,"voiceControl":false}'::jsonb
  ),
  (
    'kling-v3-text-to-video-output-video-4k-native-audio-on-voice-control-off',
    'kling-v3-text-to-video',
    'output_video',
    'output_duration_seconds',
    NULL,
    'second',
    1,
    420000,
    '{"outputResolution":"4k","nativeAudio":true,"voiceControl":false}'::jsonb
  ),
  (
    'seedance-2.0-video-provider-video-tokens-480p-720p-input-video-off',
    'seedance-2.0-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    7000000,
    '{"outputResolution":["480p","720p"],"inputIncludesVideo":false}'::jsonb
  ),
  (
    'seedance-2.0-video-provider-video-tokens-480p-720p-input-video-on',
    'seedance-2.0-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    4300000,
    '{"outputResolution":["480p","720p"],"inputIncludesVideo":true}'::jsonb
  ),
  (
    'seedance-2.0-video-provider-video-tokens-1080p-input-video-off',
    'seedance-2.0-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    7700000,
    '{"outputResolution":"1080p","inputIncludesVideo":false}'::jsonb
  ),
  (
    'seedance-2.0-video-provider-video-tokens-1080p-input-video-on',
    'seedance-2.0-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    4700000,
    '{"outputResolution":"1080p","inputIncludesVideo":true}'::jsonb
  ),
  (
    'seedance-2.0-video-provider-video-tokens-4k-input-video-off',
    'seedance-2.0-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    4000000,
    '{"outputResolution":"4k","inputIncludesVideo":false}'::jsonb
  ),
  (
    'seedance-2.0-video-provider-video-tokens-4k-input-video-on',
    'seedance-2.0-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    2400000,
    '{"outputResolution":"4k","inputIncludesVideo":true}'::jsonb
  ),
  (
    'seedance-2.0-fast-video-provider-video-tokens-480p-720p-input-video-off',
    'seedance-2.0-fast-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    5600000,
    '{"outputResolution":["480p","720p"],"inputIncludesVideo":false}'::jsonb
  ),
  (
    'seedance-2.0-fast-video-provider-video-tokens-480p-720p-input-video-on',
    'seedance-2.0-fast-video',
    'provider_video_tokens',
    'seedance_estimated_video_tokens',
    'provider_completion_tokens',
    'token',
    1000000,
    3300000,
    '{"outputResolution":["480p","720p"],"inputIncludesVideo":true}'::jsonb
  )
ON CONFLICT ("id") DO UPDATE SET
  "model_id" = excluded."model_id",
  "component" = excluded."component",
  "quantity_source" = excluded."quantity_source",
  "final_quantity_source" = excluded."final_quantity_source",
  "quantity_unit" = excluded."quantity_unit",
  "unit_quantity" = excluded."unit_quantity",
  "unit_price_usd_micros" = excluded."unit_price_usd_micros",
  "conditions" = excluded."conditions",
  "updated_at" = now();
